## Основы Python. Занятие 3. Практика NumPy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.1.0


In [3]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
#pip install pingouin


  Obtaining dependency information for pingouin from https://files.pythonhosted.org/packages/35/2e/8ca90e7edc93bc3d3bdf6daa6d5fc5ae4882994171c3db765365227e1d58/pingouin-0.5.4-py2.py3-none-any.whl.metadata
  Obtaining dependency information for pandas-flavor from https://files.pythonhosted.org/packages/67/1a/bfb5574b215f530c7ac5be684f33d60b299abbebd763c203aa31755f2fb2/pandas_flavor-0.6.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/198.9 kB ? eta -:--:--
   -- ------------------------------------- 10.2/198.9 kB ? eta -:--:--
   -- ------------------------------------- 10.2/198.9 kB ? eta -:--:--
   ------ -------------------------------- 30.7/198.9 kB 330.3 kB/s eta 0:00:01
   ------------------ -------------------- 92.2/198.9 kB 655.4 kB/s eta 0:00:01
   ---------------------------------------- 198.9/198.9 kB 1.2 MB/s eta 0:00:00


In [3]:
pip install numpy --upgrade

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/7b/5e/093592740805fe401ce49a627cc8a3f034dac62b34d68ab69db3c56bd662/numpy-2.1.0-cp311-cp311-win_amd64.whl.metadata
  Using cached numpy-2.1.0-cp311-cp311-win_amd64.whl.metadata (59 kB)
Using cached numpy-2.1.0-cp311-cp311-win_amd64.whl (12.9 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Отказано в доступе: 'C:\\Anaconda\\Lib\\site-packages\\~umpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll'
Consider using the `--user` option or check the permissions.



### Создание массива

In [3]:
# 1D
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
# 2D
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
# 3D
a = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
np.empty(3)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [14]:
np.empty([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.arange(4)

array([0, 1, 2, 3])

In [16]:
np.arange(1,4)

array([1, 2, 3])

In [17]:
np.arange(1,10,3)

array([1, 4, 7])

In [24]:
np.linspace(0, 10, num = 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Атрибуты

In [28]:
l = [1,2,3,4]
l.append(5)

l.sort()
l

[1, 2, 3, 4, 5]

In [42]:
l[3:]

[4, 5]

In [29]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
a.ndim

2

In [33]:
a.shape

(3, 4)

In [34]:
a.size

12

In [37]:
a.dtype

dtype('int64')

In [40]:
a.itemsize

8

### Срезы

In [44]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
a[0]

array([1, 2, 3, 4])

In [48]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
b[0]

array([[1, 2],
       [3, 4]])

In [50]:
a[:,2]

array([ 3,  7, 11])

In [51]:
b[:,1]

array([[3, 4],
       [7, 8]])

In [52]:
b[0,1]

array([3, 4])

In [53]:
b[:, :, 1]

array([[2, 4],
       [6, 8]])

In [56]:
a[0, 1]

np.int64(2)

In [57]:
b[0, 1, 1]

np.int64(4)

In [58]:
a[0,1]= 10
a

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a[:2]

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8]])

In [60]:
a[:2, 2:]

array([[3, 4],
       [7, 8]])

In [61]:
a[:2, 3]

array([4, 8])

In [65]:
a[-1:, -3:-1]

array([[10, 11]])

### Арифметические операции

In [66]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [67]:
a + b

array([20, 31, 42, 53])

In [68]:
a - b

array([20, 29, 38, 47])

In [69]:
a * b

array([  0,  30,  80, 150])

In [71]:
 b / a

array([0.        , 0.03333333, 0.05      , 0.06      ])

In [72]:
b ** 2

array([0, 1, 4, 9])

In [74]:
10 * np.sqrt(a)

array([44.72135955, 54.77225575, 63.2455532 , 70.71067812])

In [75]:
a < 35

array([ True,  True, False, False])

In [79]:
# Срез по логическому выражению
a[a < 35]

array([20, 30])

In [82]:
b[b%2 == 0]

array([0, 2])

In [83]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [84]:
A + B

array([[3, 1],
       [3, 5]])

In [85]:
A - B

array([[-1,  1],
       [-3, -3]])

In [86]:
A * B

array([[2, 0],
       [0, 4]])

In [87]:
A @ B

array([[5, 4],
       [3, 4]])

In [88]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [89]:
C = np.array([[1,1,1], [0,1,2]])
D = np.array([[2,0,1], [3,4,5]])
print(C)
print(D)

[[1 1 1]
 [0 1 2]]
[[2 0 1]
 [3 4 5]]


In [90]:
C * D

array([[ 2,  0,  1],
       [ 0,  4, 10]])

In [91]:
C @ D

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [93]:
C @ D.T

array([[ 3, 12],
       [ 2, 14]])

In [94]:
C.T @ D

array([[ 2,  0,  1],
       [ 5,  4,  6],
       [ 8,  8, 11]])

### Методы агрегирования

In [97]:
D.min()

np.int64(0)

In [98]:
D.max()

np.int64(5)

In [99]:
D.sum()

np.int64(15)

In [100]:
D.mean()

np.float64(2.5)

In [101]:
D.prod()

np.int64(0)

In [102]:
D.var()

np.float64(2.9166666666666665)

In [103]:
D.std()

np.float64(1.707825127659933)

In [104]:
D.sum(axis = 0)

array([5, 4, 6])

In [105]:
D.sum(axis = 1)

array([ 3, 12])

In [106]:
D.mean(axis = 0)

array([2.5, 2. , 3. ])

In [107]:
D.mean(axis = 1)

array([1., 4.])

### Случайные числа

In [109]:
np.random.default_rng(42).random([3,2])

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803],
       [0.09417735, 0.97562235]])

In [110]:
from numpy.random import default_rng

In [128]:
default_rng(42).random([2,3])

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [129]:
default_rng(42).random([2,3,2])

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

### Изменение формы массива

In [130]:
a = np.floor(10*default_rng(42).random([3,4]))
a

array([[7., 4., 8., 6.],
       [0., 9., 7., 7.],
       [1., 4., 3., 9.]])

In [131]:
a.shape

(3, 4)

In [132]:
a.ravel()

array([7., 4., 8., 6., 0., 9., 7., 7., 1., 4., 3., 9.])

In [138]:
a.reshape(6,2)

array([[7., 4.],
       [8., 6.],
       [0., 9.],
       [7., 7.],
       [1., 4.],
       [3., 9.]])

In [139]:
a.reshape(2, 3, 2)

array([[[7., 4.],
        [8., 6.],
        [0., 9.]],

       [[7., 7.],
        [1., 4.],
        [3., 9.]]])

### Объединение массивов

In [140]:
a = np.floor(10*default_rng(42).random([2,2]))
a

array([[7., 4.],
       [8., 6.]])

In [141]:
b = np.floor(10*default_rng(40).random([2,2]))
b

array([[7., 6.],
       [9., 0.]])

In [142]:
np.vstack([a,b])

array([[7., 4.],
       [8., 6.],
       [7., 6.],
       [9., 0.]])

In [143]:
np.hstack([a,b])

array([[7., 4., 7., 6.],
       [8., 6., 9., 0.]])

### Копирование

In [150]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
b = a

In [152]:
b is a

True

In [153]:
b[1,1] = 10
a

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [154]:
c = a.view()
c is a

False

In [155]:
c[1,1] = 999
a

array([[  1,   2,   3,   4],
       [  5, 999,   7,   8],
       [  9,  10,  11,  12]])

In [156]:
d = a.copy()
d is a

False

In [157]:
d[1,1] = 1000
a

array([[  1,   2,   3,   4],
       [  5, 999,   7,   8],
       [  9,  10,  11,  12]])

In [158]:
d

array([[   1,    2,    3,    4],
       [   5, 1000,    7,    8],
       [   9,   10,   11,   12]])

In [ ]:
d[]

""